import "./globals.css";
import Header from "./components/Header/Header.jsx";
import Footer from "./components/footer/FooterNavigation.jsx";



export const metadata = {
  title: "I Play Music",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="dk">
      <body className="antialiased"
        
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
