import "./globals.css";
import Header from "./components/Header/Header.jsx";
import Footer from "./components/footer/FooterNavigation.jsx";



export const metadata = {
  title: "I Play Music",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="dk">
      <body className="min-h-dvh flex flex-col antialiased overflow-hidden">
        <Header/>
        <main className="flex-1 min-h-0">{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
